[web]
  title = "Redwood RLS Demonstration"
  port = 8910
  apiUrl = "/.redwood/functions"
  includeEnvironmentVariables = []
[api]
  port = 8911
[browser]
  open = true
[generate]
  stories = false
  tests = false
